version: "3"
services:
    web:
        build: .
        expose:
            - 5000
        volumes:
            - .:/app
        environment:
          - FLASK_APP=app.py
          - FLASK_DEBUG=0
          - PYTHONUNBUFFERED=True
        command: gunicorn  -b 0.0.0.0:5000 app:app --reload
    nginx:
        build: ./nginx
        ports:
            - "5000:5000"
        depends_on:
            - web